name: 'Publish wiki'
description: 'Publish Gitbook to GitHub Pages'
author: 'Liren Tu, jdh'
branding:
  icon: 'book'
  color: 'blue'
inputs:
  github_token:
    description: 'Github token for the repo'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.client_secret }}
